### ISSUE TITLE
Missing tid in message

### ISSUE THREAD

**Issue by orion3dgames** [Innovailable/calling-signaling#2] opened 2020-07-17 06:08 UTC
Hello there, 

I've set up the signaling server, however it is returning : 

{"type":"join","status":{}} | 27 | 16:06:41.231
{"type":"hello","id":"fd025905-ee88-479c-9bd5-a63645d42560","server":"calling-signaling 1.0"} | 93 | 16:06:41.232
{"type":"error","error":"Missing tid in message"}

`const channel = new rtc.WebSocketChannel("wss://xxx.xxxxxxxx.xxx/" + encodeURI(roomName));`

What am I missing?

PS: I'm not sure what other information to provide? 

Many Thanks, Orion

**Comment by thammi** [comment] 2020-07-17 10:12
Hi,

I think the problem is that your are using another signaling protocol in rtc-lib. rtc-lib supports multiple protocols for different use cases (see signaling package/directory in rtc-lib). Please try using [easy-signaling](https://github.com/Innovailable/easy-signaling) with your example. It is a less complex signaling server (without features like calling, namespaces and invitations).

I hope this helps.

**Comment by orion3dgames** [comment] 2020-07-18 03:44
Many thanks for your answer @thammi , I will be for sure checking out **easy signaling**. 

The code is very basic at the moment at works with your signalling server. Maybe there is something obvious I'm doing wrong.

EDIT: After I wrote this, I saw and guessing the wss://easy.innovailable.eu/ is using the **easy signaling** already instead of the  **calling-signaling'** I'm using :)

EDIT 2 : Ok, that did the trick. Thanks

**Comment by orion3dgames** [comment] 2020-07-18 07:44
@thammi Could I be so bold as to ask for advice on how to implement sending peers name to each other?

``<script type="text/javascript" src="/assets/vendors/rtc-lib/rtc.dep.min.js"></script>
    <script>


        jQuery(document).ready(function($){

            connect();

            async function connect() {

                // get room name from token
                const roomName = "ROOM_NAME_123456";

                // connnect to a public signaling server using the given name
                //const channel = new rtc.WebSocketChannel("wss://easy.innovailable.eu/" + encodeURI(roomName));
                const channel = new rtc.WebSocketChannel("wss://signaling.xxxxxxxxxxxx.net/" + encodeURI(roomName));
                const signaling = new rtc.MucSignaling(channel);

                // use a public stun server
                const options = {
                    stun: "stun:stun.innovailable.eu",
                }

                // create a room
                const room = new rtc.Room(signaling, options);

                try {
                    // create a local stream from the users camera
                    const stream = await room.local.addStream({ video: true, audio: true });

                    // display that stream
                    const ve = new rtc.MediaDomElement($('video')[0], stream);

                    $('.doCloseConnection').on('click', function(){
                        room.leave();
                        stream.stop();
                        $('video').remove();
                    });

                } catch(err) {
                    alert("Unable to get stream, please give permission. You might have to go into settings if you denied before.");
                    return;
                }

                // get notified whenever we meet a new peer
                room.on('peer_joined', function(peer) {
                    console.log(peer);
                    // create a video tag for the peer
                    const view = $('<video width="300" class="mr-2 mb-2" autoplay>');
                    $('#peers').append(view);
                    const ve = new rtc.MediaDomElement(view[0], peer);

                    // remove the tag after peer left
                    peer.on('left', function() {
                        view.remove();
                    });
                });

                // join the room
                try {
                    await room.connect();
                } catch(err) {
                    alert("Unable to join room: " + err.message)
                }
            }
        });

    </script>``

**Comment by thammi** [comment] 2020-07-19 10:46
The easiest way to share a name is using the status object (a simple object stored in the signaling server) associated with the user. You can set it on the `LocalPeer` for example with `room.local.status("name", "Peter")` and your can read it from the `RemotePeer` with `peer.status("name")`. If you want to keep track of changes during the lifetime there are `status_changed` events on `RemotePeer`.

I will close this ticket now. If you have further questions please open something on rtc-lib (or easy-signaling if specific to the signaling server). If you have suggestions on how to improve the library or documentation feel free to contact us as well.

**Closed as completed by thammi** 2020-07-19 10:46 UTC

**Comment by orion3dgames** [comment] 2020-07-20 00:21
Truly great. Many thanks @thammi
